### PR TITLE
Update install instructions and fixes drawable color change for cast icon 

### PR DESCRIPTION
**Pull request by jedashford**
What we found, is that if the tintColor is set at the same time the component is added:
`<CastButton style={{width: 24, height: 24, tintColor: 'black'}} />`
,the native module throws a null pointer at:
 `GoogleCastButtonManager > ColorableMediaRouteButton.applyTint` as `mRemoteIndicatorDrawable` is null. 

After some debugging, it appears there is a delay between creating the `ColorableMediaRouteButton` and when the override method `setRemoteIndicatorDrawable` is run. 

Creating the loop inside of applyTint allows the color to be set as soon as `mRemoteIndicatorDrawable` is no longer null.

### CODE REVIEW

**Comment by petrbela** [comment]
Let me check this tonight...

**Comment by jukben** [comment]
Regarding the fix of `tint` on Android, I'd stick with this solution. https://github.com/flextv/react-native-google-cast/pull/2/commits/b25daab8bb8bf2452d5d28495a8301e4bdf3e2a2

**Comment by jedashford** [comment]
@jukben I just tested https://github.com/flextv/react-native-google-cast/commit/b25daab8bb8bf2452d5d28495a8301e4bdf3e2a2 and looks like its working great. Can you create a PR please? I closed this one.

**Comment by petrbela** [comment]
@jukben @jedashford Thanks for testing, I'll apply the fix directly in the new version.

**Comment by jedashford** [comment]
@petrbela Thanks! Sorry for the long wait, we had some pivots where I work and we're back to working on my streaming app :)

**Comment by hitaloramon** [comment]
@petrbela Accept my PR 3c802d7 too, it's working perfectly

**Pull request closed without merging**
