### PR TITLE
Add Google Cast SDK framework search path to XCodeProj

### PR DESCRIPTION
**Pull request by joshyhargreaves**
screen shot 2018-05-21 at 6 16 29 pm

I have a project which links `react-native-google-cast` into the project as a static library; it cannot find the Google Cast framework headers when compiling the project. 
Adding the Google Cast SDK src location to `framework search paths` fixes the issue as per: https://github.com/charliesbox/react-native-google-cast/issues/21#issuecomment-372065414.

If there is a way to fix this without modifying the `react-native-google-cast` project file itself I would totally do that, maybe through inheriting the framework search paths of the parent project? However setting framework search paths in react-native libraries which wrap cocoapod dependencies does seem to be fairly common, as per `rn-firebase` below, so maybe it is necessary?
screen shot 2018-05-21 at 6 06 35 pm

### CODE REVIEW

**Comment by simonayzman** [comment]
@petrbela Any thoughts on this?

**Comment by petrbela** [comment]
Hey sorry forgot to turn on notifications on this repo.

Do you use CocoaPods? We have `pod 'google-cast-sdk', '~> 3'` in Podfile, which links the `..../Pods/google-cast-sdk` route to your project automatically.

Actually, let me check with some other libraries I wrote after this one. There's a chance the configuration here is not *entirely* correct.

**Comment by simonayzman** [comment]
We do, yes. It doesn't work right off the bat after the npm dependency installation, pod dependency installation, and the linking.

Also, the npm dependency we add should point to your specific repo, not that main one, right? E.g.:

```
    "react-native-google-cast":
      "flextv/react-native-google-cast#master",
```

**Comment by petrbela** [comment]
Right, that dependency is temporary until the new version is released.

**Comment by simonayzman** [comment]
Gotcha. Thanks! Let us know if you figure anything about this search paths issue, or if the linking needs to occur differently 👍

**Comment by joshyhargreaves** [comment]
Framework search paths added as part of this PR: https://github.com/flextv/react-native-google-cast/pull/2.

The outdated Google Play Services logic that we as accidentally included in this PR, we will open another PR.

**Pull request closed without merging**
